# Generic build number, later set to commit hash by init
version: '{build}'

# Include "nodeploy" in the commit message to prevent deployment to github

# Do not build on tags
skip_tags: true
clone_depth: 1

environment:
  matrix:
  - job_name: windows_legacy
    appveyor_build_worker_image: Visual Studio 2019
#  - job_name: windows
#    appveyor_build_worker_image: Visual Studio 2019
#  - job_name: macos
#   appveyor_build_worker_image: macos
#  - job_name: linux
#    appveyor_build_worker_image: Ubuntu2004

init:
  # Set "build version number" shown in appveyor build status to the commit hash, the build number keeps it unique
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_COMMIT.substring(0,7)) ($env:APPVEYOR_BUILD_NUMBER)"
  - ps: if($Env:inhibit_deploy -eq 'true'){Write-Host "**** Deploy Inhibited ****"}

branches:
  only:
    - master

stack:
  python 3.10 # if nothing else is specified per platform, this indicates the Python version to be used

for:
-
  matrix:
    only:
      - job_name: windows_legacy
    fast_finish: false

  environment:
    PYTHON_PATH: "C:\\Python38-x64"
    QT_PATH: "c:\\qt\\5.15\\msvc2019_64"
    PYUIC: "pyuic5.exe"
    PYINSTALLER_VER: "5.5"
    BUILD_PYINSTALLER: "True"
    ARTISAN_LEGACY: "True"
    VC_REDIST: "https://aka.ms/vs/16/release/vc_redist.x64.exe"

  install:
    - cmd: echo Windows Legacy Install
    - cmd: set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
    - cmd: .ci\install-win.bat LEGACY

  build_script:
    - cmd: echo Windows Legacy Build
    - cmd: cd src
        
    #update the copyright year used by pyinstaller to set exe propertis for Windows
    - ps: $YEAR=(Get-Date).year
    - ps: gc version-metadata.yml | %{ $_ -replace "yyyy", "$YEAR" } | out-file newfile -encoding ascii
    - ps: move -force newfile version-metadata.yml

    # update the __revision__ field with the left seven of the GIT commit hash
    - ps: $GIT_VERSION=git rev-parse --verify --short HEAD
    - ps: gc artisanlib/__init__.py | %{ $_ -replace "__revision__ = '0'", "__revision__ = '$GIT_VERSION'" } | out-file newfile -encoding ascii
    - ps: move -force newfile artisanlib/__init__.py

    # run the install script
#    - cmd: build-win3-pi.bat LEGACY
     - cmd: cd

#  test_script:
#    - cmd: python -m unittest discover

#  artifacts:
#    - path: 'src\artisan-*.zip'

#  deploy_script:
#    - cmd: bash ../.ci/upload.sh artisan-*.zip

  deploy:
    - cmd: cd
    release: 'Continuous build'
    description: 'WARNING: pre-release builds may not work. Use at your own risk.'
    provider: GitHub
    auth_token:
      secure: 5NTtIMyG6aTMWDGmgG9vtaoF4fKfIecOCenVyzmogwvHz/12Bv71HwgmuykeE6bY # your encrypted token from GitHub
    #artifact: /artisan-.*\.zip/
    artifact: /.*win.*/
    draft: false
    prerelease: true
    force_update: true
#    on:
#      branch: master                 # release from master branch only
#      APPVEYOR_REPO_TAG: true        # deploy on tag push only


-
  matrix:
    only:
      - job_name: windows
    fast_finish: false

  environment:
    PYTHON_PATH: "C:\\Python310-x64"
    QT_PATH: "C:\\qt\\6.2\\msvc2019_64"
    PYUIC: "pyuic6.exe"
    PYINSTALLER_VER: "5.5"
    BUILD_PYINSTALLER: "True"
    ARTISAN_LEGACY: "False"
    VC_REDIST: "https://aka.ms/vs/17/release/vc_redist.x64.exe"

  install:
    - cmd: echo Windows Install
    - cmd: set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
    - cmd: .ci\install-win.bat

  build_script:
    - cmd: echo Windows Build
    - cmd: cd src

    #update the copyright year used by pyinstaller to set exe propertis for Windows
    - ps: $YEAR=(Get-Date).year
    - ps: gc version-metadata.yml | %{ $_ -replace "yyyy", "$YEAR" } | out-file newfile -encoding ascii
    - ps: move -force newfile version-metadata.yml

    # update the __revision__ field with the left seven of the GIT commit hash
    - ps: $GIT_VERSION=git rev-parse --verify --short HEAD
    - ps: gc artisanlib/__init__.py | %{ $_ -replace "__revision__ = '0'", "__revision__ = '$GIT_VERSION'" } | out-file newfile -encoding ascii
    - ps: move -force newfile artisanlib/__init__.py

    # run the install script
    - cmd: build-win3-pi.bat

#  test_script:
#    - cmd: python -m unittest discover

#  artifacts:
#    - path: 'src\artisan-*.zip'

  deploy_script:
    - cmd: bash ../.ci/upload.sh artisan-*.zip


-
  matrix:
    only:
      - job_name: macos
    fast_finish: false

  environment:
    ARTISAN_OS: osx
    PYTHON_V: 3.10
    PYTHONPATH: /usr/local/lib/python${PYTHON_V}
    MACOSX_DEPLOYMENT_TARGET: 10.15

  install:
    - echo "MacOS Install"
    - chmod +x .ci/*.sh

    # update the __revision__ field with the left seven of the GIT commit hash
    - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
    - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py

    # run the install script
    - .ci/install-${ARTISAN_OS}.sh

  build_script:
    - echo "MacOS Build"
    - chmod +x src/*.sh
    - chmod +x src/pylupdate6pro
    - .ci/script-${ARTISAN_OS}.sh

# unit test fails as it runs on Py3.9 while the build installs under brew isntalled Py3.10 (see build-mac3.py)
#  test_script:
#    - python -m unittest discover -s src

#  artifacts:
#    - path: 'src/artisan-*.dmg'

  deploy_script:
    - cd src
    - curl -L -O https://github.com/roasterdave/uploadtool/raw/master/upload.sh
    - bash ../.ci/upload.sh artisan-*.dmg


-
  matrix:
    only:
      - job_name: linux
    fast_finish: false

  environment:
    ARTISAN_OS: linux
    PYTHON_V: 3.10
    PYTHON_PATH: /home/appveyor/venv${PYTHON_V}/lib/python${PYTHON_V}/site-packages

  install:
    - echo "Linux Install"
    - chmod +x .ci/*.sh

    # update the __revision__ field with the left seven of the GIT commit hash
    - export GIT_VERSION=`git rev-parse --verify --short HEAD 2>/dev/null|| echo "???"`
    - sed -i'' -e "s/__revision__ = '0'/__revision__ = '$GIT_VERSION'/" src/artisanlib/__init__.py

    # run the install script
    - .ci/install-${ARTISAN_OS}.sh

  build_script:
    - echo "Linux Build"
    - chmod +x src/*.sh
    - .ci/script-${ARTISAN_OS}.sh

#  test_script:
#    - QT_QPA_PLATFORM=offscreen python -m unittest discover -s src

#  artifacts:
#    - path: 'src/artisan-*.deb'
#    - path: 'src/artisan-*.rpm'

  deploy_script:
    - cd src
    - bash ../.ci/upload.sh artisan-*.deb
    - bash ../.ci/upload.sh artisan-*.rpm
    - bash ../.ci/upload.sh artisan-*.AppImage
        
