name: "Problem Report"
description: Create a problem report to help us improve Artisan
title: "-"
labels: []

body:
  - type: markdown
    attributes:
      value: **Thanks for taking the time to fill out this bug report!**

  - type: checkboxes
    attributes:
      label: Before you hit SUBMIT please check.  To attach a file simply drag and drop it onto this report. 
      options:
        - label: >
            A sample profile *.alog file, renamed to *alog.txt is attached
        - label: >
            A settings file (Help>> Save Settings) *.aset, renamed to *.aset.txt is attached
        
  - type: input
    attributes:
      label: Artisan Version
      description: Go to "Help>> About". 
      placeholder: "Example: 2.10.1"
    validations:
      required: true

  - type: input
    attributes:
      label: Artisan Build Number
      description: Go to "Help>> About", the number in brackets (). 
      placeholder: "Example: 4b4b3fa"
    validations:
      required: false

  - type: input
    attributes:
      label: Computer OS and Version
      description: Mac/Windows/Linux + OS version.
      placeholder: "Example: macOS 10.15.3 or Windows 11"
    validations:
      required: false

  - type: input
    attributes:
      label: Connected devices or roasting machine
      description: What is connected to Artisan.
      placeholder: "Example: Probatone 5"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Problem Description
      description: A clear and concise description of the problem.  Include steps to reproduce.  Drag and drop files and screenshots here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      value: >
        1. ...

        2. ...

        3. ...
    validations:
      required: false

