blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/roundfile/yml/discussions
    about: For questions, comments or anything else please create a Discussion item.
