---
name: Feature Request
description: Suggest an idea to enhance Artisan.  If you have a question please create a Discussion.
labels: [feature request]
body:
  - type: markdown
    attributes:
      # yamllint disable rule:line-length
      value: "
        ### **Thanks for taking the time to suggest an idea to improve Artisan!  The Artisan team appreciates your support.**

        <img src='https://github.com/artisan-roaster-scope/artisan/raw/master/src/artisan.png' align='left' width='100' height='100'>
        <br clear='left'/>"
      # yamllint enable rule:line-length

  - type: textarea
    attributes:
      label: Enhancement suggestion
      description: A clear description of want you want to happen.
      placeholder: |
        Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thanks for your support!"

